#!/usr/bin/env bash
# test-swarm-integration-corrected.sh
# Validates swarm mode configuration with CORRECT structure
# Part of Multi-Agent Ralph Loop v2.81.1

# Don't exit on error - we want to run all tests
set +e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Test counters
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

# Test functions
test_pass() {
  local msg="$1"
  echo -e "${GREEN}✓ PASS${NC}: $msg"
  ((TESTS_PASSED++))
  ((TESTS_RUN++))
}

test_fail() {
  local msg="$1"
  echo -e "${RED}✗ FAIL${NC}: $msg"
  ((TESTS_FAILED++))
  ((TESTS_RUN++))
}

test_info() {
  local msg="$1"
  echo -e "${YELLOW}ℹ INFO${NC}: $msg"
  ((TESTS_RUN++))
}

echo "=========================================="
echo "Swarm Mode Test - CORRECTED v2.81.1"
echo "=========================================="
echo ""

# Test 1: Verify settings.json exists
echo "Test 1: Check settings.json exists"
if [[ -f ~/.claude-sneakpeek/zai/config/settings.json ]]; then
  test_pass "settings.json exists at correct path"
else
  test_fail "settings.json not found at expected path"
  exit 1
fi
echo ""

# Test 2: Verify defaultMode is delegate (in permissions, NOT root)
echo "Test 2: Check permissions.defaultMode configuration"
DEFAULT_MODE=$(jq -r '.permissions.defaultMode // "none"' ~/.claude-sneakpeek/zai/config/settings.json 2>/dev/null || echo "none")
if [[ "$DEFAULT_MODE" == "delegate" ]]; then
  test_pass "permissions.defaultMode is 'delegate' (swarm mode enabled)"
else
  test_fail "permissions.defaultMode is '$DEFAULT_MODE' (expected 'delegate')"
fi
echo ""

# Test 3: Clarify environment variables behavior
echo "Test 3: Environment variables behavior"
test_info "CLAUDE_CODE_AGENT_* are set DYNAMICALLY by Claude Code"
test_info "They do NOT need to be pre-configured in settings.json"
echo "  - Claude Code sets them automatically when spawning teammates"
echo "  - Each teammate gets unique AGENT_ID generated by system"
echo "  - Variables are specific to each teammate instance"
echo ""

# Test 4: Verify agent definitions exist
echo "Test 4: Check agent definitions"
AGENT_COUNT=$(ls -1 .claude/agents/*.md 2>/dev/null | wc -l)
if [[ "$AGENT_COUNT" -ge 10 ]]; then
  test_pass "Found $AGENT_COUNT agent definitions (>= 10)"
else
  test_fail "Found only $AGENT_COUNT agent definitions (expected >= 10)"
fi
echo ""

# Test 5: Verify swarm mode is documented in orchestrator
echo "Test 5: Check orchestrator.md swarm documentation"
if grep -q "team_name.*orchestration-team\|launchSwarm.*true" .claude/commands/orchestrator.md 2>/dev/null; then
  test_pass "orchestrator.md documents swarm mode parameters"
else
  test_fail "orchestrator.md missing swarm mode documentation"
fi
echo ""

# Test 6: Verify TeammateTool documentation exists
echo "Test 6: Check TeammateTool documentation"
if [[ -f ~/.claude-sneakpeek/zai/tweakcc/system-prompts/tool-description-teammatetool.md ]]; then
  test_pass "TeammateTool documentation exists"
else
  test_fail "TeammateTool documentation not found"
fi
echo ""

# Test 7: Verify swarm mode prompts exist
echo "Test 7: Check swarm mode system prompts"
SWARM_PROMPTS=(
  "agent-prompt-exit-plan-mode-with-swarm.md"
  "system-reminder-delegate-mode-prompt.md"
  "system-reminder-team-coordination.md"
)
SWARM_PROMPTS_FOUND=0
for prompt in "${SWARM_PROMPTS[@]}"; do
  if [[ -f ~/.claude-sneakpeek/zai/tweakcc/system-prompts/$prompt ]]; then
    ((SWARM_PROMPTS_FOUND++))
  fi
done
if [[ $SWARM_PROMPTS_FOUND -eq ${#SWARM_PROMPTS[@]} ]]; then
  test_pass "All ${#SWARM_PROMPTS[@]} swarm mode prompts found"
else
  test_fail "Only $SWARM_PROMPTS_FOUND/${#SWARM_PROMPTS[@]} prompts found"
fi
echo ""

# Test 8: Information about CLI parameters
echo "Test 8: CLI parameters for swarm mode"
test_info "teammateCount is a CLI parameter, NOT a settings.json field"
test_info "It's passed to: /orchestrator 'task' --teammateCount 3"
test_info "swarmTimeoutMinutes is also a CLI parameter"
echo ""

# Summary
echo "=========================================="
echo "Test Summary"
echo "=========================================="
echo "Tests Run:    $TESTS_RUN"
echo -e "Tests Passed: ${GREEN}$TESTS_PASSED${NC}"
echo -e "Tests Failed: ${RED}$TESTS_FAILED${NC}"
echo ""

if [[ $TESTS_FAILED -eq 0 ]]; then
  echo -e "${GREEN}✓ Swarm mode is PROPERLY CONFIGURED${NC}"
  echo ""
  echo "Configuration Summary:"
  echo "  • permissions.defaultMode: $DEFAULT_MODE ✓"
  echo "  • Environment variables: Set dynamically by Claude Code ✓"
  echo "  • Agent definitions: $AGENT_COUNT available ✓"
  echo "  • Documentation: Complete ✓"
  echo ""
  echo "Swarm mode is READY for use in:"
  echo "  • /orchestrator"
  echo "  • /loop"
  echo "  • /edd"
  echo "  • /bug"
  echo "  • All other agents"
  exit 0
else
  echo -e "${RED}✗ Some tests failed${NC}"
  exit 1
fi
